version: "3.9"
services:
  tradebot1:
    extends:
      service: tradebot-common--tinkoff
      file: docker-base-services.yaml
    volumes: [ ./tradebot1.env:/usr/src/app/.env ]
    ports: [ 4268:4268 ]
  tradebot2:
    extends:
      service: tradebot-common--tinkoff
      file: docker-base-services.yaml
    volumes: [ ./tradebot2.env:/usr/src/app/.env ]
    ports: [ 4269:4268 ]
  dashboard:
    build: ./trade-bots-dashboard/
    image: badlabs/trade-bots-dashboard
    ports:
      - 8080:80